# Conclusion and Outlook

The proposed workflow in this thesis paper was developed in the framework of the Project Seminar **'Treelines of the World'**. The overall objective of this project was to detect *Treelines*, using an automated remote sensing approach. To approach this question, an overview of methodological approach to the detection of ATEs was laid down in **Chapter 2 - Overview**, to understand what how this question is approached. It has emerged, that the fundamental step towards the automated detection of ATEs is the actual detection of trees. 

Thus the aim of the combined workflow developed in this project (**Chapter 3 - Methodology**, **Figure 5**.) was to detect trees with shallow learning, because the development of a **Deep Learning Framework** would've exceeded the scope and possibilities of a seminar thesis. An **Object-based Image Analysis (OBIA)** sub-workflow was developed in case of LiDAR data availability (which is sadly mostly not the case) and a **Pixel-based Image Analysis (PBIA)** in the case of the availability of Aerial Imagery or Satellite data (which is usually the case). If both data sets are available, then the results of the PBIA can be compared with the result of the Segmentation based on cell-statistics.
Both the results of the **Pixel-based Image Analysis (PBIA)** and the **Object-based Image Analysis (OBIA)** are successful and valid, according to their limitations. They deliver robust information fundamental for further analysis for patch-based and landscape metrics which can be done e.g. in R (`landscapemetrics` [@hesselbarthLandscapemetricsOpensourceTool2019]) or with **fragstats**. 
In the case of the **Object-based Image Analysis (OBIA)**, different Segmentation algorithms should be investigated further, not only *'Watershed Segmentation'* with markers.
In the case of **Pixel-based Image Analysis (PBIA)**, *'Random Forest'* works really reliable. In the case of the input data, a more detailed spectral resolution of the different bands should be investigated by using *Hyperspectral* data sets. Thus also tree species identification would be possible. 

From methodological point of view the next step forward would be the use of *Deep Learning Architectures* for the detection of trees and tree species (and also the other classes). From Computer Vision perspective three different approaches exist: **Image Classification** (classifying the whole image), **Object Detection** (detecting objects in a bounding box) and **Object Segmentation** (detecting objects with bounding boxes and segments for the detected objects). 

An example of **Image Classification** was performed lately by @egliCNNBasedTreeSpecies2020, where a light-weight CNN architecture was built for classifiying 4 tree species (oak, beech, larch and spruce) in the Marburg Open Forest. The end product of the approach is the generation of a gridded product which can be analysed further. 
Based on @weinsteinIndividualTreeCrownDetection2019 and @weinsteinGeographicGeneralizationAirborne2019 the [*`DeepForest` python package*](https://deepforest.readthedocs.io/en/latest/landing.html) was developed to detect individual tree crowns from RGB Aerial Imagery using *Object Detection*. The predicted bounding boxes match individual trees. \
Both **Image Classification** and **Object Detection** are well established and well working methods and work well for tree detection, but **Object Segmentation** goes a step further. The two main directions are ***Semantic Segmentation*** and ***Instance Segmentation***. During ***Semantic Segmentation*** a class label is assigned to every pixel in the image. Pixels with the same class label are treated as a single class. **U-net** (@ronnebergerUNetConvolutionalNetworks2015b) is an example for Semantic Segmentation. ***Instance Segmentation*** on the other hand first performs object detection to extract bounding boxes around object instances and then performs binary segmentation inside each bounding box. Thus, each object is treated as a separate instance. a widely used ***Instance Segmentation*** Architecture is **Mask R-CNN** (@heMaskRCNN2017a). \
Depending on what the purpose of the detection is, an appropriate method should be chosen. In the case of tree detection the exact shape and size of the trees is important, to be able to derive metrics from it. This suggests, that **Object Segmentation** is the way to go. In Biodiversity research, Forestry and Remote Sensing different solutions and implementation exist for tree detection using **Object Segmentation**. **TreeSegNet** (@yueTreeSegNetAdaptiveTree2018) e.g. is a specialized implementation of **DeepUnet** (@liDeepUNetDeepFully2017) based on the original **U-net** (***Semantic Segmentation***) for tree detection. As an example of ***Instance Segmentation*** e.g. **Mask R-CNN** was used to automatically detect dead trees (@chiangDeepLearningBasedAutomated2020). These studies point into the direction, in which the automated tree detection and ultimately the detection of Alpine Treeline Ecotones should go. With the constant development of **Deep Learning Architectures** solutions for complex detection problems will be more and more achievable. 
